# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEcGtI5wQFH7mfq14qZpIKSGTTTl4DS-
"""



"""#Question 1 : Create an object named student with the following properties:
● name: "Rahul"
● age: 21
● courses: an array containing "Math", "Physics", and "Chemistry"
Then, perform the following operations:
1. Add a new property grade with the value "A".
2. Update the age to 22.
3. Delete the courses property.

"""

let obj = {
    name: "Rahul",
    age: 21,
    courses: ["Math", "Physics", "chemistry"]
}
//Adding new property as grade
obj.grade = "A";

//Updating the age
obj.age = 22;

//deleting the propert naming course
delete obj.courses;

console.log(obj);

"""#Question 2: Write a function checkEligibility that takes an age as a parameter
and returns:
● "Eligible" if age is 18 or above
● "Not Eligible" if age is below 18
Use an if-else statement
"""

function checkEligibility(age){
if(age<=18){
    console.log("Eligible ");
}
else{
    console.log("Not Eligible");
}
}

console.log(checkEligibility(56));

"""#Question 3: Write a function getDayName that takes a number (1-7) and returns the corresponding day of the week. Use a switch statement."""

function getDayName(number) {
  switch (number) {
    case 1:
      return "Sunday";
    case 2:
      return "Monday";
    case 3:
      return "Tuesday";
    case 4:
      return "Wednesday";
    case 5:
      return "Thursday";
    case 6:
      return "Friday";
    case 7:
      return "Saturday";
    default:
      return "Invalid input";
  }
}

console.log(getDayName(3));
console.log(getDayName(7));
console.log(getDayName(9));

"""#Question 4: Rewrite the checkEligibility function from Question 2 using the ternary operator."""

function checkEligibility( age){
 return (age>=18 ? "Eligible" : "Not Eligible");
}

console.log(checkEligibility(18));

"""#Question 5: Given an array numbers = [1, 2, 3, 4, 5], perform the following:
1. Use a for loop to print each number.
2. Use a while loop to print each number.
3. Use a for-in loop to print each index.
4. Use a for-of loop to print each number.
"""

let arr = [1,2,3,4,5];

//Using for loop to print each number
for(let i =1; i<=arr.length;i++){
    console.log(i);

}

//Using while loop
let i =1;
while(i<+arr.length){
    console.log(i);
    i++;
}

//using for-in loop
for (let index in arr) {
   console.log(index);

    }

    //using for-of loop
    for (let num of arr) {
        console.log(num);

    }

"""#Question 6: Explain what functions are in JavaScript and provide an example of a function that adds two numbers.

        -----> Functions: Function is block of coode which is executed when it is called.
        Using function in Javascript Provides the code reusability.
        

"""

function add( a, b){
    return(a+b);
}

console.log(add(5,7));

"""#Question 7: Convert the add function from Question 6 into an arrow function.

"""

const addNumbers = (a, b) => a + b;

let result = addNumbers(5, 3);
console.log(result);

"""#Question 8: Write a function greet that takes a name and a callback function. The greet function should call the callback with the name.

"""

function greet(name, callback){
callback(name);
}

function sayhello(name){
    console.log("Hello" + name +"!");
}
greet("PW", sayhello);

"""#Question 9: Given the array:
const fruits = ["apple", "banana", "cherry"];
1. What is the length of the array?
2. Add "date" to the end of the array using the length property.
"""

const fruits = ["apple", "banana", "cherry"];

//length of array
console.log(fruits.length);

//adding date using length property
fruits[fruits.length] = "date";
console.log(fruits);

"""#Question 10: Given the string text = " Hello World! ", perform the following:
1. Trim the whitespace.
2. Convert to uppercase.
3. Check if it includes "World".

"""

let text = " Hello World! ";
console.log(text.trim());

console.log(text.toUpperCase());

console.log(text.includes("World"));

"""#Question 11: Given the array numbers = [1, 2, 3, 4, 5], perform the following:
1. Add 6 to the end.
2. Remove the first element.
3. Find the index of 4.
4. Check if all numbers are greater than 0
"""

let arr = [1, 2, 3, 4, 5];

arr.push(6);
console.log(arr);

arr.shift();
console.log(arr);


console.log(arr.indexOf(4));
console.log(allGreaterThanZero = arr.every(num => num>0));





